# StaffUtilsPlus Plugin Configuration
name: StaffUtilsPlus
version: 1.0.1
main: me.hexett.staffUtilsPlus.StaffUtilsPlus
api-version: 1.21
description: A comprehensive staff utilities plugin for Minecraft servers
author: Hexett
website: https://github.com/hexett/StaffUtilsPlus
depend: [ProtocolLib]

# Commands
commands:
  ban:
    description: Ban a player from the server
    usage: /ban <player> [reason] [duration]
    aliases: [tempban]
    permission: staffutils.ban
    permission-message: "&cYou don't have permission to use this command!"

  kick:
    description: Kick a player from the server
    usage: /kick <player>
    permission: staffutils.kick
    permission-message: "&cYou don't have permission to use this command!"
  
  unban:
    description: Unban a player from the server
    usage: /unban <player>
    permission: staffutils.unban
    permission-message: "&cYou don't have permission to use this command!"
  
  mute:
    description: Mute a player on the server
    usage: /mute <player> [reason] [duration]
    aliases: [tempmute]
    permission: staffutils.mute
    permission-message: "&cYou don't have permission to use this command!"
  
  unmute:
    description: Unmute a player on the server
    usage: /unmute <player>
    permission: staffutils.unmute
    permission-message: "&cYou don't have permission to use this command!"
  
  ipban:
    description: IP ban a player from the server
    usage: /ipban <player> [reason] [duration]
    aliases: [tempipban]
    permission: staffutils.ipban
    permission-message: "&cYou don't have permission to use this command!"
  
  unbanip:
    description: Unban an IP address from the server
    usage: /unbanip <ip-address>
    permission: staffutils.unbanip
    permission-message: "&cYou don't have permission to use this command!"
  
  notes:
    description: Manage player notes
    usage: /notes <player> [add/remove] [content/id]
    permission: staffutils.notes
    permission-message: "&cYou don't have permission to use this command!"

  vanish:
    description: Puts a player in vanish
    permission: staffutils.vanish
    permission-message: "&cYou don't have permission to use this command!"
  
  warnings:
    description: Manage player warnings
    usage: /warnings <player> [add/remove] [reason/severity/id]
    permission: staffutils.warnings
    permission-message: "&cYou don't have permission to use this command!"
  
#  staffmenu:
#    description: Open the staff menu
#    usage: /staffmenu
#    permission: staffutils.menu
#    permission-message: "&cYou don't have permission to use this command!"
  
  help:
    description: Show help information
    usage: /help [page]
    aliases: [h, ?, staffhelp]
    permission: staffutils.help
    permission-message: "&cYou don't have permission to use this command!"
  
  reload:
    description: Reload the plugin configuration
    usage: /reload
    aliases: [staffreload]
    permission: staffutils.reload
    permission-message: "&cYou don't have permission to use this command!"



# Permissions
permissions:
  staffutils.*:
    description: Gives access to all StaffUtilsPlus commands
    children:
      staffutils.ban: true
      staffutils.unban: true
      staffutils.mute: true
      staffutils.unmute: true
      staffutils.ipban: true
      staffutils.kick: true
      staffutils.unbanip: true
      staffutils.notes: true
      staffutils.warnings: true
      staffutils.menu: true
      staffutils.reload: true
      staffutils.debug: true
      staffutils.notify.ban: true
      staffutils.notify.mute: true
      staffutils.notify.ipban: true
      staffutils.vanish: true
    default: op
  
  staffutils.ban:
    description: Allows banning players
    default: op
  
  staffutils.unban:
    description: Allows unbanning players
    default: op

  staffutils.kick:
    description: Allows kicking players
    default: op

  staffutils.mute:
    description: Allows muting players
    default: op
  
  staffutils.unmute:
    description: Allows unmuting players
    default: op
  
  staffutils.ipban:
    description: Allows IP banning players
    default: op
  
  staffutils.unbanip:
    description: Allows unbanning IP addresses
    default: op
  
  staffutils.notes:
    description: Allows managing player notes
    default: op
  
  staffutils.warnings:
    description: Allows managing player warnings
    default: op
  
  staffutils.menu:
    description: Allows accessing the staff menu
    default: op
  
  staffutils.reload:
    description: Allows reloading the plugin
    default: op
  
  staffutils.debug:
    description: Allows debug commands
    default: op
  
  staffutils.notify.ban:
    description: Receives ban notifications
    default: op
  
  staffutils.notify.mute:
    description: Receives mute notifications
    default: op
  
  staffutils.notify.ipban:
    description: Receives IP ban notifications
    default: op

  staffutils.notify.kick:
    description: Revieves kick notifications
    default: op

  staffutils.vanish:
    description: Allows players to enter vanish and see vanished players.
    default: op
